---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[jenkins-chefci::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    driver_config:
      network:
      # Use DHCP to be save for multiple instances
      - ["private_network", {type: "dhcp"}]
      # Assign IP directly, if you start only one instance at a time
      # - ["private_network", {ip: "192.168.88.23"}]
