---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[jenkins-chefci::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
