---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048
  network:
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true
    # Use DHCP to be save for multiple instances
    - ["private_network", {type: "dhcp"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
  - name: debian-8.6
    run_list:
      - recipe[apt]

suites:
  - name: essentials
    run_list:
      - recipe[jenkins-chefci::default]
    verifier:
      inspec_tests:
        - test/smoke/default
  - name: full
    attributes:
      jenkins_chefci:
        github_credentials:
          login: <%= ENV['JENKINS_GITHUB_LOGIN'] %>
          token: <%= ENV['JENKINS_GITHUB_TOKEN'] %>
    run_list:
      - recipe[jenkins-chefci::full]
    verifier:
      inspec_tests:
        - test/smoke/full
